/* DO NOT EDIT THIS FILE - it is machine generated */
#ifndef _AVIF_IMAGEIO_H_
#define _AVIF_IMAGEIO_H_

#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Encoder Options
 */
JNIEXPORT jlong JNICALL Java_com_github_avifimageio_AvifEncoderOptions_createConfig
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_github_avifimageio_AvifEncoderOptions_deleteConfig
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_github_avifimageio_AvifEncoderOptions_getQuality
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_github_avifimageio_AvifEncoderOptions_setQuality
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_github_avifimageio_AvifEncoderOptions_getSpeed
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_github_avifimageio_AvifEncoderOptions_setSpeed
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_github_avifimageio_AvifEncoderOptions_getBitDepth
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_github_avifimageio_AvifEncoderOptions_setBitDepth
  (JNIEnv *, jobject, jint);

JNIEXPORT jboolean JNICALL Java_com_github_avifimageio_AvifEncoderOptions_isLossless
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_github_avifimageio_AvifEncoderOptions_setLossless
  (JNIEnv *, jobject, jboolean);

/*
 * Decoder Options
 */
JNIEXPORT jlong JNICALL Java_com_github_avifimageio_AvifDecoderOptions_createOptions
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_github_avifimageio_AvifDecoderOptions_deleteOptions
  (JNIEnv *, jclass, jlong);

JNIEXPORT jboolean JNICALL Java_com_github_avifimageio_AvifDecoderOptions_isIgnoreIcc
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_github_avifimageio_AvifDecoderOptions_setIgnoreIcc
  (JNIEnv *, jobject, jboolean);

JNIEXPORT jboolean JNICALL Java_com_github_avifimageio_AvifDecoderOptions_isIgnoreExif
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_github_avifimageio_AvifDecoderOptions_setIgnoreExif
  (JNIEnv *, jobject, jboolean);

/*
 * Avif main class
 */
JNIEXPORT jobject JNICALL Java_com_github_avifimageio_Avif_getInfoNative
  (JNIEnv *, jclass, jbyteArray, jint, jint);

JNIEXPORT jobject JNICALL Java_com_github_avifimageio_Avif_decodeNative
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

JNIEXPORT jobject JNICALL Java_com_github_avifimageio_Avif_decodeFrameNative
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jint);

JNIEXPORT jbyteArray JNICALL Java_com_github_avifimageio_Avif_encodeRGBNative
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jint);

JNIEXPORT jbyteArray JNICALL Java_com_github_avifimageio_Avif_encodeRGBANative
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jint);

JNIEXPORT jbyteArray JNICALL Java_com_github_avifimageio_Avif_getExifNative
  (JNIEnv *, jclass, jbyteArray, jint, jint);

JNIEXPORT jbyteArray JNICALL Java_com_github_avifimageio_Avif_getIccProfileNative
  (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif

#endif /* _AVIF_IMAGEIO_H_ */
